<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Deletequiz.aspx.cs" Inherits="ProjectDesignTemplate.admin.Deletequiz" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css"/>
    <style>
      
        .links{
                width: 88%;
                height: 60%;
                display: flex;
                align-items: center;
                justify-content: center;
                flex-direction: column;
            }
            .menuLinks{
                height: 25%;
                width: 100%;
                justify-content: center;
                display: flex;
                align-items: center;
                margin-bottom: 20px;
   
            }
            .menuLinks.border{
                border: 1px solid white !important;
                border-radius: 17px !important;
            }
             .cardContainer{
                height:100vh;
                display:flex;
                justify-content:center;
                align-items:center;
                
            }
             .RowContainer{
                 margin:80px auto;
             }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row no-gutters">
            <div class="col-6 col-md-2 bg-primary vh-100 d-flex align-items-center justify-content-center sticky-top flex-column" >
               
                <div class="links d-flex flex-column">
                 <a href="dashboard.aspx" class="menuLinks  text-white text-decoration-none ">Home</a>
                 <a href="addcategory.aspx" class="menuLinks  text-white text-decoration-none">Add Category</a>
                 <a href="Addquiz.aspx" class="menuLinks  text-white text-decoration-none">Add Question</a>
    
                 <a href="SelectCategory.aspx" class="menuLinks  text-white text-decoration-none border" >Edit Question</a>
                 <a href="../home.aspx" class="menuLinks  text-white text-decoration-none btn btn-outline-danger text-white " >Log Out</a>
     
             </div>
               
            </div>
       <div class="col-12 col-sm-6 col-md-10 overflow-scroll">
               <section>
                  <div class="container ">
                    <div class="row ">
                        <div class="col-12 col-lg-8">
       <form id="form1" runat="server">
                                 <div>
       <asp:GridView ID="deleteGridView" Text="myGridy" runat="server" AutoGenerateColumns="False" DataKeyNames="qid" DataSourceID ="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CssClass="table table-bordered table-condensed table-responsive table-hover w-100" Width="500px">
           <Columns>
               <asp:BoundField DataField ="qid" HeaderText ="qid" SortExpression="ID" InsertVisible="False" ReadOnly="True" />
               <asp:BoundField DataField ="qname" HeaderText ="qname" SortExpression="qname" />
               <asp:BoundField DataField ="ans1" HeaderText ="ans1" SortExpression="ans1" />
               <asp:BoundField DataField ="ans2" HeaderText ="ans2" SortExpression="ans2" />
               <asp:BoundField DataField ="ans3" HeaderText ="ans3" SortExpression="ans3" />
               <asp:BoundField DataField ="ans4" HeaderText ="ans4" SortExpression="ans4" />
               <asp:BoundField DataField="correct" HeaderText="correct" SortExpression="correct" />
               <asp:BoundField DataField="level" HeaderText="level" SortExpression="level" /> 
           </Columns>
       </asp:GridView> 
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                 SelectCommand="SELECT * FROM [quiz] WHERE [category] =@category and [level]= @level" UpdateCommand ="UPDATE [quiz] SET [qname]= @qname, [ans1]=@ans1,[ans2]=@ans2,[ans3]=@ans3, [ans4]=@ans4,[correct]=@correct,[level]=@level WHERE [qid]=@qid  " DeleteCommand="Delete FROM [quiz] WHERE [qid]=@qid">
                <SelectParameters>
                    <asp:SessionParameter Name="category" SessionField="category" Type="String"/>
                     <asp:SessionParameter Name="level" SessionField="level" Type="String"/>
                </SelectParameters>
            </asp:SqlDataSource>
     </div>
                        <div>

                    </div>
    
    
    </form>
                        </div>
                    </div>
                  </div>
                </section>
        </div>
             </div>
        
    </div>
</body>
</html>
